---
- name: Patch Windows Servers with Security Updates
  hosts: all
  gather_facts: yes
  vars:
    ansible_user: Administrator
    ansible_password: P@ssw0rd123
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985

  tasks:
    - name: Install all security updates
      win_updates:
        category_names:
          - SecurityUpdates
        reboot: yes
