---
- name: Patch Windows Servers (ignore non-critical errors)
  hosts: all
  gather_facts: yes
  vars:
    ansible_user: Administrator
    ansible_password: P@ssw0rd123
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985

  tasks:
    - name: Install security and critical updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: no
      register: win_update_result
      # Only fail if the module actually reports a failure
      failed_when: win_update_result.failed and "'No updates' not in win_update_result.msg"

    - name: Reboot if updates require it
      win_reboot:
        reboot_timeout: 3600
      when: win_update_result.reboot_required



